trigger:
  branches:
    include:
      - main  # adjust this to your main branch name
  paths:
    include:
      - azure_jumpstart_hcibox/*

parameters:
- name: ResourceGroupName
  displayName: 'Resource Group Name'
  type: string
  default: 'hcibox-test'
- name: AzureSubscription
  displayName: 'Azure Subscription'
  type: string
  default: 'HCIBox-ServiceConnection'
- name: githubAccount
  displayName: 'githubAccount'
  type: string
  default: 'ldabas-msft'
- name: githubBranch
  displayName: 'githubBranch'
  type: string
  default: 'main'

variables:
- group: hcibox-deployment
- name: ResourceGroupName
  value: ${{parameters.ResourceGroupName}}
- name: githubAccount
  value: ${{parameters.githubAccount}}
- name: githubBranch
  value: ${{parameters.githubBranch}}

pool:
  vmImage: 'windows-latest'

steps:
- task: AzurePowerShell@5
  displayName: 'Deploy resource group'
  inputs:
    azureSubscription: ${{parameters.AzureSubscription}}
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Write-Host "Running deployment from machine $(hostname) and public IP $(irm ifconfig.me/ip)"
      $RGname = "$(ResourceGroupName)"
      New-AzResourceGroup -Name $RGname -Location "eastus"

- task: AzurePowerShell@5
  displayName: 'Deploy Bicep template'
  inputs:
    azureSubscription: ${{parameters.AzureSubscription}}
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Write-Host "Deploying to $(ResourceGroupName)"
      $githubAccount = "$(githubAccount)"
      $githubBranch = "$(githubBranch)"
      if ($githubAccount -ne "microsoft") {
        Write-Host "Checking out $githubAccount/$githubBranch"
        git remote add upstream https://github.com/$($githubAccount)/azure_jumpstart_hcibox.git
        git fetch upstream
        git checkout -b $githubBranch upstream/$githubBranch
      }
      New-AzResourceGroupDeployment -Name HCIBox `
      -ResourceGroupName $(ResourceGroupName) `
      -TemplateFile azure_jumpstart_hcibox/bicep/main.bicep `
      -TemplateParameterObject @{
          spnClientId = "$(spnClientId)"
          spnClientSecret = "$(spnClientSecret)"
          spnTenantId = "$(spnTenantId)"
          spnProviderId = "$(spnProviderId)"
          windowsAdminUsername = "arcdemo"
          windowsAdminPassword = "$(windowsAdminPassword)"
          logAnalyticsWorkspaceName = "HCIBox-Workspace"
          deployBastion = $false
          autoDeployClusterResource = $true
          autoUpgradeClusterResource = $false
          githubAccount = "$(githubAccount)"
          githubBranch = "$(githubBranch)"
          location = "eastus"
      }