trigger:
  branches:
    include:
    - main

variables:
  - group: hcibox-deployment  # Must contain all variables below
  - name: spnClientId
    value: ${{ variables.spnClientId }}
  - name: spnClientSecret
    value: ${{ variables.spnClientSecret }}
  - name: spnTenantId
    value: ${{ variables.spnTenantId }}
  - name: spnProviderId
    value: ${{ variables.spnProviderId }}
  - name: subscriptionId
    value: ${{ variables.subscriptionId }}
  - name: resourceGroupName
    value: ${{ variables.resourceGroupName }}
  - name: location
    value: 'eastus'
  - name: windowsAdminUsername
    value: ${{ variables.windowsAdminUsername }}
  - name: windowsAdminPassword
    value: ${{ variables.windowsAdminPassword }}
  - name: logAnalyticsWorkspaceName
    value: ${{ variables.logAnalyticsWorkspaceName }}
  - name: deployBastion
    value: ${{ variables.deployBastion }}
  - name: autoDeployClusterResource
    value: ${{ variables.autoDeployClusterResource }}
  - name: autoUpgradeClusterResource
    value: ${{ variables.autoUpgradeClusterResource }}
  - name: githubAccount
    value: ${{ variables.githubAccount }}
  - name: githubBranch
    value: ${{ variables.githubBranch }}

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'HCIBox-ServiceConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Debug: Print environment variables
      Write-Host "Debug: Printing environment variables..."
      Write-Host "RESOURCEGROUPNAME: $env:RESOURCEGROUPNAME"
      Write-Host "LOCATION: $env:LOCATION"
      Write-Host "Pipeline variable syntax: $(resourceGroupName)"
      
      # Create resource group
      Write-Host "Creating resource group: $env:RESOURCEGROUPNAME in $env:LOCATION"
      az group create --name "$env:RESOURCEGROUPNAME" --location "$env:LOCATION"
      
      # Debug: Check if resource group was created
      Write-Host "Checking resource group..."
      az group show --name "$env:RESOURCEGROUPNAME"
      
      # Deploy main template
      Write-Host "Starting deployment to resource group: $(resourceGroupName)"
      az deployment group create `
        --resource-group "$(resourceGroupName)" `
        --template-file "$(System.DefaultWorkingDirectory)/azure_jumpstart_hcibox/artifacts/main.bicep" `
        --parameters `
          spnClientId="$(spnClientId)" `
          spnClientSecret="$(spnClientSecret)" `
          spnTenantId="$(spnTenantId)" `
          spnProviderId="$(spnProviderId)" `
          windowsAdminUsername="$(windowsAdminUsername)" `
          windowsAdminPassword="$(windowsAdminPassword)" `
          logAnalyticsWorkspaceName="$(logAnalyticsWorkspaceName)" `
          deployBastion="$(deployBastion)" `
          autoDeployClusterResource="$(autoDeployClusterResource)" `
          autoUpgradeClusterResource="$(autoUpgradeClusterResource)" `
          githubAccount="$(githubAccount)" `
          githubBranch="$(githubBranch)" `
          location="$(location)"