trigger:
  branches:
    include:
    - main

variables:
  - group: hcibox-deployment  # Must contain all variables below
  - name: spnClientId
    value: $(spnClientId)
  - name: spnClientSecret
    value: $(spnClientSecret)
  - name: spnTenantId
    value: $(spnTenantId)
  - name: spnProviderId
    value: $(spnProviderId)
  - name: subscriptionId
    value: $(subscriptionId)
  - name: resourceGroupName
    value: $(resourceGroupName)
  - name: location
    value: 'eastus'
  - name: windowsAdminUsername
    value: $(windowsAdminUsername)
  - name: windowsAdminPassword
    value: $(windowsAdminPassword)
  - name: logAnalyticsWorkspaceName
    value: $(logAnalyticsWorkspaceName)
  - name: deployBastion
    value: $(deployBastion)
  - name: autoDeployClusterResource
    value: $(autoDeployClusterResource)
  - name: autoUpgradeClusterResource
    value: $(autoUpgradeClusterResource)
  - name: githubAccount
    value: $(githubAccount)
  - name: githubBranch
    value: $(githubBranch)

pool:
  vmImage: 'windows-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'HCIBox-ServiceConnection'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Write-Host "Checking required variables..."
      Write-Host "resourceGroupName: $(resourceGroupName)"
      Write-Host "location: $(location)"
      Write-Host "spnClientId: $(spnClientId)"
      Write-Host "spnClientSecret: ***"
      Write-Host "spnTenantId: $(spnTenantId)"
      Write-Host "spnProviderId: $(spnProviderId)"
      Write-Host "windowsAdminUsername: $(windowsAdminUsername)"
      Write-Host "windowsAdminPassword: ***"
      Write-Host "logAnalyticsWorkspaceName: $(logAnalyticsWorkspaceName)"
      Write-Host "deployBastion: $(deployBastion)"
      Write-Host "autoDeployClusterResource: $(autoDeployClusterResource)"
      Write-Host "autoUpgradeClusterResource: $(autoUpgradeClusterResource)"
      Write-Host "githubAccount: $(githubAccount)"
      Write-Host "githubBranch: $(githubBranch)"
      
      # Create resource group
      Write-Host "Creating resource group: $(resourceGroupName) in $(location)"
      New-AzResourceGroup -Name "$(resourceGroupName)" -Location "$(location)"
      
      # Deploy main template
      Write-Host "Starting deployment to resource group: $(resourceGroupName)"
      New-AzResourceGroupDeployment -Name HCIBox `
        -ResourceGroupName "$(resourceGroupName)" `
        -TemplateFile "$(System.DefaultWorkingDirectory)/azure_jumpstart_hcibox/artifacts/main.bicep" `
        -TemplateParameterObject @{
          spnClientId = "$(spnClientId)"
          spnClientSecret = "$(spnClientSecret)"
          spnTenantId = "$(spnTenantId)"
          spnProviderId = "$(spnProviderId)"
          windowsAdminUsername = "$(windowsAdminUsername)"
          windowsAdminPassword = "$(windowsAdminPassword)"
          logAnalyticsWorkspaceName = "$(logAnalyticsWorkspaceName)"
          deployBastion = [System.Convert]::ToBoolean("$(deployBastion)")
          autoDeployClusterResource = [System.Convert]::ToBoolean("$(autoDeployClusterResource)")
          autoUpgradeClusterResource = [System.Convert]::ToBoolean("$(autoUpgradeClusterResource)")
          githubAccount = "$(githubAccount)"
          githubBranch = "$(githubBranch)"
          location = "$(location)"
        }