trigger:
  branches:
    include:
    - main

parameters:
- name: resourceGroupName
  type: string
  default: 'hcibox-test'
- name: location
  type: string
  default: 'eastus'

variables:
  - group: hcibox-deployment  # Variable group containing secrets
  - name: resourceGroupName
    value: ${{ parameters.resourceGroupName }}
  - name: location
    value: ${{ parameters.location }}

pool:
  vmImage: 'windows-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'HCIBox-ServiceConnection'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Write-Host "Checking required variables..."
      
      # Store variables in PowerShell variables to avoid expansion issues
      $resourceGroupName = "$(resourceGroupName)"
      $location = "$(location)"
      $spnClientId = "$(spnClientId)"
      $spnClientSecret = "$(spnClientSecret)"
      $spnTenantId = "$(spnTenantId)"
      $spnProviderId = "$(spnProviderId)"
      $windowsAdminUsername = "$(windowsAdminUsername)"
      $windowsAdminPassword = "$(windowsAdminPassword)"
      $logAnalyticsWorkspaceName = "$(logAnalyticsWorkspaceName)"
      $deployBastion = [System.Convert]::ToBoolean("$(deployBastion)")
      $autoDeployClusterResource = [System.Convert]::ToBoolean("$(autoDeployClusterResource)")
      $autoUpgradeClusterResource = [System.Convert]::ToBoolean("$(autoUpgradeClusterResource)")
      $githubAccount = "$(githubAccount)"
      $githubBranch = "$(githubBranch)"

      Write-Host "resourceGroupName: $resourceGroupName"
      Write-Host "location: $location"
      Write-Host "spnClientId: $spnClientId"
      Write-Host "spnClientSecret: ***"
      Write-Host "spnTenantId: $spnTenantId"
      Write-Host "spnProviderId: $spnProviderId"
      Write-Host "windowsAdminUsername: $windowsAdminUsername"
      Write-Host "windowsAdminPassword: ***"
      Write-Host "logAnalyticsWorkspaceName: $logAnalyticsWorkspaceName"
      Write-Host "deployBastion: $deployBastion"
      Write-Host "autoDeployClusterResource: $autoDeployClusterResource"
      Write-Host "autoUpgradeClusterResource: $autoUpgradeClusterResource"
      Write-Host "githubAccount: $githubAccount"
      Write-Host "githubBranch: $githubBranch"
      
      # Create resource group
      Write-Host "Creating resource group: $resourceGroupName in $location"
      New-AzResourceGroup -Name $resourceGroupName -Location $location -Force
      
      # Deploy main template
      Write-Host "Starting deployment to resource group: $resourceGroupName"
      New-AzResourceGroupDeployment -Name HCIBox `
        -ResourceGroupName $resourceGroupName `
        -TemplateFile "$(System.DefaultWorkingDirectory)/azure_jumpstart_hcibox/artifacts/main.bicep" `
        -TemplateParameterObject @{
          spnClientId = $spnClientId
          spnClientSecret = $spnClientSecret
          spnTenantId = $spnTenantId
          spnProviderId = $spnProviderId
          windowsAdminUsername = $windowsAdminUsername
          windowsAdminPassword = $windowsAdminPassword
          logAnalyticsWorkspaceName = $logAnalyticsWorkspaceName
          deployBastion = $deployBastion
          autoDeployClusterResource = $autoDeployClusterResource
          autoUpgradeClusterResource = $autoUpgradeClusterResource
          githubAccount = $githubAccount
          githubBranch = $githubBranch
          location = $location
        }