trigger:
  branches:
    include:
    - main

variables:
  - group: hcibox-deployment  # Must contain all variables below
  - name: spnClientId
    value: $(spnClientId)
  - name: spnClientSecret
    value: $(spnClientSecret)
  - name: spnTenantId
    value: $(spnTenantId)
  - name: spnProviderId
    value: $(spnProviderId)
  - name: subscriptionId
    value: $(subscriptionId)
  - name: resourceGroupName
    value: $(resourceGroupName)
  - name: location
    value: 'eastus'
  - name: windowsAdminUsername
    value: $(windowsAdminUsername)
  - name: windowsAdminPassword
    value: $(windowsAdminPassword)
  - name: logAnalyticsWorkspaceName
    value: $(logAnalyticsWorkspaceName)
  - name: deployBastion
    value: $(deployBastion)
  - name: autoDeployClusterResource
    value: $(autoDeployClusterResource)
  - name: autoUpgradeClusterResource
    value: $(autoUpgradeClusterResource)
  - name: githubAccount
    value: $(githubAccount)
  - name: githubBranch
    value: $(githubBranch)

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'HCIBox-ServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    addSpnToEnvironment: true
    inlineScript: |
      echo "Checking required variables..."
      echo "resourceGroupName: $(resourceGroupName)"
      echo "location: $(location)"
      echo "spnClientId: $(spnClientId)"
      echo "spnClientSecret: ***"
      echo "spnTenantId: $(spnTenantId)"
      echo "spnProviderId: $(spnProviderId)"
      echo "windowsAdminUsername: $(windowsAdminUsername)"
      echo "windowsAdminPassword: ***"
      echo "logAnalyticsWorkspaceName: $(logAnalyticsWorkspaceName)"
      echo "deployBastion: $(deployBastion)"
      echo "autoDeployClusterResource: $(autoDeployClusterResource)"
      echo "autoUpgradeClusterResource: $(autoUpgradeClusterResource)"
      echo "githubAccount: $(githubAccount)"
      echo "githubBranch: $(githubBranch)"
      
      # Create resource group
      echo "Creating resource group: $(resourceGroupName) in $(location)"
      az group create --name "$(resourceGroupName)" --location "$(location)"
      
      # Deploy main template
      echo "Starting deployment to resource group: $(resourceGroupName)"
      az deployment group create \
        --resource-group "$(resourceGroupName)" \
        --template-file "$(System.DefaultWorkingDirectory)/azure_jumpstart_hcibox/artifacts/main.bicep" \
        --parameters \
          spnClientId="$(spnClientId)" \
          spnClientSecret="$(spnClientSecret)" \
          spnTenantId="$(spnTenantId)" \
          spnProviderId="$(spnProviderId)" \
          windowsAdminUsername="$(windowsAdminUsername)" \
          windowsAdminPassword="$(windowsAdminPassword)" \
          logAnalyticsWorkspaceName="$(logAnalyticsWorkspaceName)" \
          deployBastion="$(deployBastion)" \
          autoDeployClusterResource="$(autoDeployClusterResource)" \
          autoUpgradeClusterResource="$(autoUpgradeClusterResource)" \
          githubAccount="$(githubAccount)" \
          githubBranch="$(githubBranch)" \
          location="$(location)"